devices:
  - name: radio1
    tcp: 192.168.1.110

mqtt_servers:
  - name: external
    server: localhost
    port: 1883



pipelines:
  owntracks:
    - owntracks_plugin:
        server_name: external
        tid_table:
          "1234": ["Van", "GV"]
          "-5678": ["Home", "HR"]
