on:
  push:
    tags:
      - "*"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Build and publish image
        uses: zmingxie/docker_buildx@master
        with:
          publish: true
          imageName: gwhittington/meshtastic-bridge:latest
          dockerHubUser: gwhittington
          dockerHubPassword: ${{secrets.DOCKER_HUB}}
